run:
  timeout: 5m
  go: "1.23"
  modules-download-mode: readonly
  exclude-dirs:
    - .github

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - godot
    - goprintffuncname
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  gosec:
    excludes:
      - G404 # Use of weak random number generator
      - G601 # Implicit memory aliasing in for loop

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - dupl
        - gocyclo
    - path: internal/models/
      linters:
        - gomnd
    - path: cmd/
      linters:
        - gomnd
        - gocyclo

  max-issues-per-linter: 0
  max-same-issues: 0

